# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Paperless-ngx installation tasks
  when: paperless_enabled | bool
  tags:
    - setup-all
    - setup-paperless
    - install-all
    - install-paperless
  block:
    - name: Validate Paperless-ngx configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Paperless-ngx
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Paperless-ngx uninstallation tasks
  when: not paperless_enabled | bool
  tags:
    - setup-all
    - setup-paperless
  block:
    - name: Uninstall Paperless-ngx
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
