# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: paperless-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        paperless_debug_service_enabled: false

        # Variables for Paperless-ngx
        paperless_uid: 1000
        paperless_gid: 1000
        paperless_scheme: http
        paperless_hostname: localhost
        paperless_container_labels_traefik_enabled: false
        paperless_container_http_host_bind_port: 3000
        paperless_database_type: mariadb
        paperless_secret_key: secret

        # Variables required for Paperless-ngx to connect to the MariaDB database (via Unix socket)
        paperless_database_mariadb_hostname: "{{ mariadb_connection_hostname }}"
        paperless_database_mariadb_port: "{{ mariadb_connection_port }}"
        paperless_database_mariadb_username: my_database_username
        paperless_database_mariadb_password: my_database_password
        paperless_database_name: paperless
        paperless_systemd_required_services_list_auto: |
          {{
            (['mariadb.service'])
          }}

        # Variables required for Paperless-ngx to connect to the Valkey data-store
        paperless_redis_hostname: "{{ valkey_identifier }}"
        paperless_container_additional_networks_custom:
          - "{{ valkey_container_network }}"
        paperless_systemd_required_services_list_custom:
          - "{{ valkey_identifier }}.service"

        # Variables for MariaDB
        mariadb_uid: 1000
        mariadb_gid: 1000
        mariadb_root_password: mariadb_password
        mariadb_container_network: "{{ paperless_container_network }}"
        mariadb_managed_databases: |
          {{
            [{
              'name': paperless_database_name,
              'username': paperless_database_mariadb_username,
              'password': paperless_database_mariadb_password,
            }]
          }}

        # Variables for Valkey
        valkey_uid: 1000
        valkey_gid: 1000
        valkey_arch: amd64
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
scenario:
  # See: https://docs.ansible.com/projects/molecule/configuration/?h=test_sequence#scenario
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # Disable idempotence test for now due to ansible-role-mariadb
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
